<a href="https://colab.research.google.com/github/hilaltekgz/Yaz-muh-guncel-konular-proje/blob/master/Hava-Kalitesi-%C4%B0ndeksi-Hesaplama.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [4]:
!pip install python-aqi

Requirement already satisfied: python-aqi in /usr/local/lib/python3.6/dist-packages (0.6.1)

In [5]:
# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels as sm

# Set plot style
plt.style.use('seaborn')

# Set plot size
plt.rcParams['figure.figsize'] = [8,6]


# Load the data from a CSV file
df = pd.read_csv("/content/drive/My Drive/guncel/Kocaeli_Orj.csv")

# Print the DataFrame info
df.info()

# Print the DataFrame
df

print ("Rows     : " ,df.shape[0])
print ("Columns  : " ,df.shape[1])
print ("\nFeatures : \n" ,df.columns.tolist())
print ("\nMissing values :  ", df.isnull().sum())
print ("\nUnique values :  \n",df.nunique())

# tarih sütununu tarih saatine dönüştür
PM10 = df['Kocaeli-PM10']
Tarih = df['Tarih']
PM10 = pd.DataFrame(PM10)

veri_PM10 = PM10.join(df['Tarih'],how='inner')

veri_PM10

df["Tarih"] = pd.to_datetime(df["Tarih"])
# Set the index of the DataFrame to the date column
#df.set_index("Tarih", inplace = True)

# Print DataFrame summary
df.info()

No2 = df['Kocaeli-NO2']
Tarih = df['Tarih']
No2 = pd.DataFrame(No2)
veri_No2 = No2.join(df['Tarih'],how='inner')
veri_No2.set_index("Tarih", inplace = True)

# Print DataFrame
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3287 entries, 0 to 3286
Data columns (total 66 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              3287 non-null   int64
 1   id                      3287 non-null   int64
 2   Tarih                   3287 non-null   object
 3   Kocaeli-PM10            3287 non-null   float64
 4   Kocaeli-PM10Debi        3287 non-null   float64
 5   Kocaeli-SO2             3287 non-null   float64
 6   Kocaeli-NO2             3287 non-null   float64
 7   Kocaeli-NOX             3287 non-null   float64
 8   Kocaeli-NO              3287 non-null   float64
 9   Kocaeli-O3              3287 non-null   float64
 10  Kocaeli-HavaSicakligi   3287 non-null   float64
 11  Kocaeli-RuzgarHizi      3287 non-null   float64
 12  Kocaeli-BagilNem        3287 non-null   float64
 13  Kocaeli-KabinSicakligi  3287 non-null   float64
 14  Kocaeli-KabinNem        3287 non-null   float64
 15  Kocaeli-PM25            0 non-null      float64
 16  Kocaeli-PM25Debi        0 non-null      float64
 17  Gebze-SO2               411 non-null    float64
 18  Gebze-M10               412 non-null    float64
 19  Gebze-PM10Debi          3287 non-null   float64
 20  Gebze-NO2               3287 non-null   float64
 21  Gebze-NOX               3287 non-null   float64
 22  Gebze-NO                3287 non-null   float64
 23  Gebze-O3                411 non-null    float64
 24  Gebze-HavaSicakligi     3287 non-null   float64
 25  Gebze-RuzgarHizi        3287 non-null   float64
 26  Gebze-BagilNem          411 non-null    float64
 27  Yenikoy-SO2             2132 non-null   float64
 28  Yenikoy-M10             2132 non-null   float64
 29  Yenikoy-PM10Debi        3287 non-null   float64
 30  Yenikoy-NO2             3287 non-null   float64
 31  Yenikoy-NOX             3287 non-null   float64
 32  Yenikoy-NO              3287 non-null   float64
 33  Yenikoy-O3              2132 non-null   float64
 34  Yenikoy-HavaSicakligi   3287 non-null   float64
 35  Yenikoy-RuzgarHizi      3287 non-null   float64
 36  Yenikoy-BagilNem        2132 non-null   float64
 37  Yenikoy-PM25Debi        0 non-null      float64
 38  Yenikoy-PM25            0 non-null      float64
 39  Alikahya-SO2            2132 non-null   float64
 40  Alikahya-M10            2132 non-null   float64
 41  Alikahya-PM10Debi       3287 non-null   float64
 42  Alikahya-NO2            3287 non-null   float64
 43  Alikahya-NOX            3287 non-null   float64
 44  Alikahya-NO             3287 non-null   float64
 45  Alikahya-O3             0 non-null      float64
 46  Alikahya-HavaSicakligi  3287 non-null   float64
 47  Alikahya-RuzgarHizi     3287 non-null   float64
 48  Alikahya-BagilNem       2132 non-null   float64
 49  Alikahya-PM25Debi       0 non-null      float64
 50  Alikahya-PM25           0 non-null      float64
 51  Golcuk-SO2              2132 non-null   float64
 52  Golcuk-M10              77 non-null     float64
 53  Golcuk-PM10Debi         3287 non-null   float64
 54  Golcuk-NO2              3287 non-null   float64
 55  Golcuk-NOX              3287 non-null   float64
 56  Golcuk-NO               3287 non-null   float64
 57  Golcuk-O3               2132 non-null   float64
 58  Golcuk-HavaSicakligi    3287 non-null   float64
 59  Golcuk-RuzgarHizi       3287 non-null   float64
 60  Golcuk-BagilNem         2132 non-null   float64
 61  Golcuk-PM25Debi         3287 non-null   float64
 62  Golcuk-PM25             3287 non-null   float64
 63  Year                    3287 non-null   int64
 64  Month                   3287 non-null   int64
 65  Day                     3287 non-null   int64
dtypes: float64(60), int64(5), object(1)
memory usage: 1.7+ MB
Rows     :  3287
Columns  :  66

Features :
 ['Unnamed: 0', 'id', 'Tarih', 'Kocaeli-PM10', 'Kocaeli-PM10Debi', 'Kocaeli-SO2', 'Kocaeli-NO2', 'Kocaeli-NOX', 'Kocaeli-NO', 'Kocaeli-O3', 'Kocaeli-HavaSicakligi', 'Kocaeli-RuzgarHizi', 'Kocaeli-BagilNem', 'Kocaeli-KabinSicakligi', 'Kocaeli-KabinNem', 'Kocaeli-PM25', 'Kocaeli-PM25Debi', 'Gebze-SO2', 'Gebze-M10', 'Gebze-PM10Debi', 'Gebze-NO2', 'Gebze-NOX', 'Gebze-NO', 'Gebze-O3', 'Gebze-HavaSicakligi', 'Gebze-RuzgarHizi', 'Gebze-BagilNem', 'Yenikoy-SO2', 'Yenikoy-M10', 'Yenikoy-PM10Debi', 'Yenikoy-NO2', 'Yenikoy-NOX', 'Yenikoy-NO', 'Yenikoy-O3', 'Yenikoy-HavaSicakligi', 'Yenikoy-RuzgarHizi', 'Yenikoy-BagilNem', 'Yenikoy-PM25Debi', 'Yenikoy-PM25', 'Alikahya-SO2', 'Alikahya-M10', 'Alikahya-PM10Debi', 'Alikahya-NO2', 'Alikahya-NOX', 'Alikahya-NO', 'Alikahya-O3', 'Alikahya-HavaSicakligi', 'Alikahya-RuzgarHizi', 'Alikahya-BagilNem', 'Alikahya-PM25Debi', 'Alikahya-PM25', 'Golcuk-SO2', 'Golcuk-M10', 'Golcuk-PM10Debi', 'Golcuk-NO2', 'Golcuk-NOX', 'Golcuk-NO', 'Golcuk-O3', 'Golcuk-HavaSicakligi', 'Golcuk-RuzgarHizi', 'Golcuk-BagilNem', 'Golcuk-PM25Debi', 'Golcuk-PM25', 'Year', 'Month', 'Day']

Missing values :   Unnamed: 0          0
id                  0
Tarih               0
Kocaeli-PM10        0
Kocaeli-PM10Debi    0
                   ..
Golcuk-PM25Debi     0
Golcuk-PM25         0
Year                0
Month               0
Day                 0
Length: 66, dtype: int64

Unique values :
 Unnamed: 0          3287
id                  3287
Tarih               3287
Kocaeli-PM10        1688
Kocaeli-PM10Debi    2834
                    ...
Golcuk-PM25Debi      194
Golcuk-PM25         1641
Year                   9
Month                 12
Day                   31
Length: 66, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3287 entries, 0 to 3286
Data columns (total 66 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              3287 non-null   int64
 1   id                      3287 non-null   int64
 2   Tarih                   3287 non-null   datetime64[ns]
 3   Kocaeli-PM10            3287 non-null   float64
 4   Kocaeli-PM10Debi        3287 non-null   float64
 5   Kocaeli-SO2             3287 non-null   float64
 6   Kocaeli-NO2             3287 non-null   float64
 7   Kocaeli-NOX             3287 non-null   float64
 8   Kocaeli-NO              3287 non-null   float64
 9   Kocaeli-O3              3287 non-null   float64
 10  Kocaeli-HavaSicakligi   3287 non-null   float64
 11  Kocaeli-RuzgarHizi      3287 non-null   float64
 12  Kocaeli-BagilNem        3287 non-null   float64
 13  Kocaeli-KabinSicakligi  3287 non-null   float64
 14  Kocaeli-KabinNem        3287 non-null   float64
 15  Kocaeli-PM25            0 non-null      float64
 16  Kocaeli-PM25Debi        0 non-null      float64
 17  Gebze-SO2               411 non-null    float64
 18  Gebze-M10               412 non-null    float64
 19  Gebze-PM10Debi          3287 non-null   float64
 20  Gebze-NO2               3287 non-null   float64
 21  Gebze-NOX               3287 non-null   float64
 22  Gebze-NO                3287 non-null   float64
 23  Gebze-O3                411 non-null    float64
 24  Gebze-HavaSicakligi     3287 non-null   float64
 25  Gebze-RuzgarHizi        3287 non-null   float64
 26  Gebze-BagilNem          411 non-null    float64
 27  Yenikoy-SO2             2132 non-null   float64
 28  Yenikoy-M10             2132 non-null   float64
 29  Yenikoy-PM10Debi        3287 non-null   float64
 30  Yenikoy-NO2             3287 non-null   float64
 31  Yenikoy-NOX             3287 non-null   float64
 32  Yenikoy-NO              3287 non-null   float64
 33  Yenikoy-O3              2132 non-null   float64
 34  Yenikoy-HavaSicakligi   3287 non-null   float64
 35  Yenikoy-RuzgarHizi      3287 non-null   float64
 36  Yenikoy-BagilNem        2132 non-null   float64
 37  Yenikoy-PM25Debi        0 non-null      float64
 38  Yenikoy-PM25            0 non-null      float64
 39  Alikahya-SO2            2132 non-null   float64
 40  Alikahya-M10            2132 non-null   float64
 41  Alikahya-PM10Debi       3287 non-null   float64
 42  Alikahya-NO2            3287 non-null   float64
 43  Alikahya-NOX            3287 non-null   float64
 44  Alikahya-NO             3287 non-null   float64
 45  Alikahya-O3             0 non-null      float64
 46  Alikahya-HavaSicakligi  3287 non-null   float64
 47  Alikahya-RuzgarHizi     3287 non-null   float64
 48  Alikahya-BagilNem       2132 non-null   float64
 49  Alikahya-PM25Debi       0 non-null      float64
 50  Alikahya-PM25           0 non-null      float64
 51  Golcuk-SO2              2132 non-null   float64
 52  Golcuk-M10              77 non-null     float64
 53  Golcuk-PM10Debi         3287 non-null   float64
 54  Golcuk-NO2              3287 non-null   float64
 55  Golcuk-NOX              3287 non-null   float64
 56  Golcuk-NO               3287 non-null   float64
 57  Golcuk-O3               2132 non-null   float64
 58  Golcuk-HavaSicakligi    3287 non-null   float64
 59  Golcuk-RuzgarHizi       3287 non-null   float64
 60  Golcuk-BagilNem         2132 non-null   float64
 61  Golcuk-PM25Debi         3287 non-null   float64
 62  Golcuk-PM25             3287 non-null   float64
 63  Year                    3287 non-null   int64
 64  Month                   3287 non-null   int64
 65  Day                     3287 non-null   int64
dtypes: datetime64[ns](1), float64(60), int64(5)
memory usage: 1.7 MB

      Unnamed: 0    id      Tarih  Kocaeli-PM10  ...  Golcuk-PM25  Year  Month  Day
0              0     0 2010-01-01          7.93  ...        30.79  2010      1    1
1              1     1 2010-01-02          8.99  ...        12.82  2010      1    2
2              2     2 2010-01-03         21.38  ...        29.08  2010      1    3
3              3     3 2010-01-04         15.61  ...        38.86  2010      1    4
4              4     4 2010-01-05         17.14  ...        23.40  2010      1    5
...          ...   ...        ...           ...  ...          ...   ...    ...  ...
3282        3282  3282 2018-12-27         30.25  ...        39.97  2018     12   27
3283        3283  3283 2018-12-28         14.80  ...        39.97  2018     12   28
3284        3284  3284 2018-12-29          7.83  ...        39.97  2018     12   29
3285        3285  3285 2018-12-30         13.36  ...        39.97  2018     12   30
3286        3286  3286 2018-12-31         40.25  ...        39.97  2018     12   31

[3287 rows x 66 columns]

In [10]:
import aqi
myaqi = aqi.to_iaqi(aqi.POLLUTANT_PM10, '58.05', algo=aqi.ALGO_EPA)
print('Hava Kalite İndeksi \n',myaqi)

Hava Kalite İndeksi
 52